steps:
- id: go_build
  name: golang
  args: ['go', 'build', '-ldflags=-s -w', '.']
  env: ["CGO_ENABLED=0"]
- id: go_security
  name: "securego/gosec"
  args: ["/"]
  env: ["GOPATH=."]
- id: docker_image_build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/anz-test', '.']
- id: cloud_run_deploy
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'anz-test',
    '--image', 'gcr.io/$PROJECT_ID/anz-test',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars=LASTCOMMITSHA=$COMMIT_SHA, VERSION=$TAG_NAME' ## Uses builtin substitutions for version and commit SHA
    ]
- id: gke_deploy ## Requires modifying IAM permissions https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-gke#required_iam_permissions
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args: [
    'run',
    '--filename=/kubernetes/',
    '--location=us-central1',
    '--cluster=standard-cluster-1'
  ]