steps:
- id: go_build
  name: golang
  args: ['go', 'build', '-ldflags=-s -w', '.']
  env: ["CGO_ENABLED=0"]
- id: go_security
  name: "securego/gosec"
  args: ["/"]
  env: ["GOPATH=."]
- id: docker_image_build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/anz-test', '.']
images: ['gcr.io/$PROJECT_ID/anz-test']
artifacts:
  objects:
    location: 'gs://anz-test/'
    paths: ['anz-test']