---
apiVersion: v1
kind: Namespace
metadata:
  name: anz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: anz-test-config
  namespace: anz
  labels:
    app: anz-test
data:
  VERSION: 1.2.3
  LASTCOMMITSHA: abc1234abc1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anz-test
  namespace: anz
  labels:
    app: anz-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anz-test
  template:
    metadata:
      labels:
        app: anz-test
    spec:
      containers:
      - name: anz-test
        image: gcr.io/ira-nz/anz-test:latest
        ports:
        - containerPort: 8080
        env:
          - name: "VERSION"
            valueFrom:
              configMapKeyRef:
                key: "VERSION"
                name: "anz-test-config"
          - name: "LASTCOMMITSHA"
            valueFrom:
              configMapKeyRef:
                key: "LASTCOMMITSHA"
                name: "anz-test-config"
---
kind: Service
apiVersion: v1
metadata:
  name: anz-test
spec:
  selector:
    app: anz-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: anz-test-hpa
  namespace: anz
  labels:
    app: anz-test-app
spec:
  scaleTargetRef:
    kind: Deployment
    name: anz-test
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80